### ISSUE TITLE
Add the original MIT license to the project

### ISSUE THREAD

**Issue by whoanuragverma** [abhitcr1/wordpredictor-abhit-dsa#2]
Hi, @abhitcr1 

Since you have cloned my project which was licensed under the **MIT licence** which clearly stated that the original copyright notice must be attached with any part(s) containing my work. 

I request you to fix this, otherwise I will go for a **_DMCA takedown notice._**

**Comment by abhitcr1** [comment]
Lavda lo air naach lo
